### ISSUE TITLE
Create Media Queries

### ISSUE THREAD

**Issue by kschmelter1** [kschmelter1/my-new-portfolio#1]
Need to include media queries at natural breakpoints for various size screens starting at mobile.

**Comment by ericconrad** [comment]
The easiest way to do this is go mobile first. Get all of your content in, style it up for small screens, and then re-arrange as needed as the screen size increases. Don't worry about making breakpoints for specific screen sizes, worry about making breakpoints for when your content needs them (e.g. too much white-space).

**Comment by kschmelter1** [comment]
Yeah that's what I meant by natural breakpoint. I'm going to close this issue just because I've got the main navigation breaks in place and will just add more as needed.
